sudo: required
language: ruby
services:
- docker
env:
  global:
  - IMAGE_NAME=ringcentral/maven
  - secure: "Y0P/2w2ADi8qujt4g14BEN3VRqhxuyhtfmal7aK2GLufxfubmHeHbhOcj9p2A6343q6R4yskRp4AIh6DDadIBpQNK9pvBUS2Pd5uf0PeB9fcY9Z+PpuLjFwdnMThDgejyrtfPwSHYG8I8af8tVSrbGxQJ/Aqa04mwRlXbwZPzrgkLcH8F3qk+c1jsOMdQulx1TzwVsT1G9drVWI12zHfIpjVARZyygxl08lSN9o/3IaUcWhelx9aA+K5EC7gLXDs6QyBLb1zdtbslR/NDD91JzWf53Xcu2+CCZW656z6wwr4VCLXmNXr3wZ70scjbTWK7f/MlVU1dl62GcVPbwgHc3ZsJRsmRqrXjN/oc2RXywkJXcuI8iT0svLv39rKjUCvLA/fWIM6mJxEpjtFXsdaXqnKfgw/U9z5kxWJSjD9WRneJFNLtNZ1L7JhjP7rQD1Q9UlbRIWrV/EOdRSC7pXeBsQ08oUxUkXO/5IMVHF3mM3Jb3xJ/bOsQix+JUZQxMRTlwZDHYhdVzdDJFnsZVdplIEO1RF5JpgDjAnZM9mtIzemdLyusW59ABf7GaXzaTiXhvsHBt8QlCJ7MVzaBNZdHe38vLDw9TnOV2m8rzoL0HN6K+5KfbGCQgGOhUfifNC8l9lKhJ5KIDr5lRyJMd4SlTANppRi4aZ18SOeFEGYohg=" # DOCKER_USERNAME
  - secure: "tMz4ZT+RN4+V/6z39/WAinuGVACgt4/bXWj8ak8YypfBlLxj3gd4l7I3PVelujDzAJDgWlbcP6nOL8/npN4/ZHZgnrfxRv1VlJgL8D71aD4hBgxz5ag25TWsA3joVzK6wmWuB0YIzaaSoyGQzo4XmW7k1rUQGUwC8a9Ik6573GKGp3C3ErMVdXucQgkb6Pra3kqnevq+M0iZNp2BXcqSWO/0r/M3/RUc5HwMRri6763ZcxbKxzLvmVS5n2hqau6GTPyyx5mTCKxLtuD7lnF+DAA8cDf3KKjBC4WWm6aFNMXFzf6jUoBwXwN5cWgoTTxc9ruw/BRWzYkowbuSvD0d92LnIB/GC1hzsCodUfUudeC/rbwGclFH8uRXCjz0bIb1o5zEFP0VtLy2cPb3fp3zs/F1a/Id2r7rws4Sb9fY3SqUIC96VoOzgXkL7zQZaEIJgW/cpGphrhDtBD7HQNLeFSeVuy73RAxK39L0SbWnUa5ef1LoAJ/IwNmNkr4cnqPTeCrjWC4q+4ToTYkN4Fz6JZkucWOn3dvQwQL7WgCqL9gsGtY4ljCtc8q1BsrQVfDolIJVYtKQeHODPaw3fdJIRo92LVeXv1K0pdHrAlVY970zmPcaTDFWT7vd9V0YU64J2da8nywgXpwkkHNdRGcwefUgcVlWHNlcgP0dRTuzSNk=" # DOCKER_PASSWORD
before_script:
- cd jdk8
- version="$(awk -F= '/MAVEN_VERSION=/ {print $2}' Dockerfile | cut -d " " -f 1)"
- base_version="jdk$(awk -F '[:]' '/FROM/ {print $2}' Dockerfile)"
script:
- docker build -t "$IMAGE_NAME" .
after_script:
- docker images
before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}-${base_version}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}" && docker push "${IMAGE_NAME}:${version}-${base_version}"
  on:
    branch: master
